### ISSUE TITLE
Reconnect on disconnect ?

### ISSUE THREAD

**Issue by Power2All** [jellysquid3/gitlab-discord-bot#5]
Sometimes bot disconnect randomly from Discord, but keeps running as if nothing went wrong.
Can this be solved ?

**Comment by jellysquid3** [comment]
The initial release of the project had a lot of issues and collected a bit of dust. I'll be pushing commits for a complete revamp tonight which uses webhooks instead of the Bot API, which should fix this issue.

**Comment by jellysquid3** [comment]
This issue should be fixed with the massive overhaul I've just pushed to the repository.
