### ISSUE TITLE
Error when testing hook

### ISSUE THREAD

**Issue by BrainStone** [jellysquid3/gitlab-discord-bot#8]
I setup the bot and the hook and when I tested it I got this response:

```Hook executed successfully but returned HTTP 404 <!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <title>Error</title> </head> <body> <pre>Cannot POST /api/v1/GitLab-BungeeChat/</pre> </body> </html> ```

Using latest GitLab and Bot

**Comment by jellysquid3** [comment]
You should be POSTing to `/api/v1/webhook/GitLab-BungeeChat`, not `/api/v1/GitLab-BungeeChat`.

**Comment by BrainStone** [comment]
Thanks. That was it :facepalm:
